### ISSUE TITLE
Criação de um code guidelines

### ISSUE THREAD

**Issue by eubyt** [soberanatv/soberanatv.github.io#22]
Acho válido a criação de um "CONTRIBUTING" com regras de padronização de código e nomes de commit no repositório, muitas pessoas podem querer ajudar a contribuir e futuramente podemos ter um frankenstein em questão de bagunça.

Deixo aqui algumas referências:
1. https://github.com/Chatterino/chatterino2/blob/master/CONTRIBUTING.md
2. https://github.com/BrasilAPI/BrasilAPI/blob/main/CONTRIBUTING.md
3. https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md

**Comment by Azhariel** [comment]
Obrigado pela sugestão camarada @eubyt , demorou mas chegou e agora só vai! 🚀
