### ISSUE TITLE
Dominio soberana.tv

### ISSUE THREAD

**Issue by benmezger** [soberanatv/soberanatv.github.io#64]
Boa tarde, 

Notei que esse site é soberanatv.github.io. Existe alguma razão de por que não é usado o soberana.tv que esta no [perfil](https://github.com/soberanatv)? Atualmente, soberana.tv redireciona para o .github.io, mas tem como usar um proprio dominio no Github pages. https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

Não seria melhor manter um padrão?

**Comment by EduSe7en42** [comment]
acho que deva ser porque o registro do domínio deva ser caro, não?

**Comment by benmezger** [comment]
> acho que deva ser porque o registro do domínio deva ser caro, não?

O dominio já existe, ele só está configurado para redirecionar

**Comment by tarcisioe** [comment]
No momento é só um redirect porque foi configurado às pressas. Vou tentar configurar isso corretamente hoje. Valeu pelo toque camaradas o>

**Comment by tarcisioe** [comment]
Domínio configurado e ajuste feito pra não ter problema com o domínio na hora de carregar o css (#65).
