### ISSUE TITLE
Outros projetos

### ISSUE THREAD

**Issue by jayypluss** [soberanatv/soberanatv.github.io#8]
Sabem dizer se há alguma discussão de tocar outros projetos de organização da Soberana como este? 
Tava vendo se podia ajudar em algo mas esse site parece que já tá bem sólido, não sei se tem outros projetos nesse sentido que eu possa ajudar.

**Comment by Azhariel** [comment]
@jayypluss Salve, camarada!
Estamos organizando mais alguns projetos através do [Discord](https://discord.gg/soberana). Inclusive, uma das sugestões foi justamente trazer as discussões de lá pra cá, através da feature de organização. Pra ficar atualizado nesse momento de transição, recomendo ver o nosso canal de `#tecnologia` dentro do Discord, onde há diversos tópicos sobre os projetos. Qualquer dúvida também pode enviar por lá!

**Comment by jayypluss** [comment]
Eu vim através de lá mas não soube achar esses projetos, o que achei foi esse repositório só. 
Tem alguma palavra chave que você recomendaria eu pesquisar pra achar eles lá? 
Vou dar uma olhada depois...

**Comment by Azhariel** [comment]
> Eu vim através de lá mas não soube achar esses projetos, o que achei foi esse repositório só. Tem alguma palavra chave que você recomendaria eu pesquisar pra achar eles lá? Vou dar uma olhada depois...

Sim! É que os tópicos ficam um pouco escondidos, tem que clicar no botão ```#```, no canto superior direito, dentro do canal de tecnologia, para listar todos
![image](https://user-images.githubusercontent.com/9439404/191411761-53d6676f-ca83-4a1b-a7f0-e59728fdbcc5.png)
