### ISSUE TITLE
Escrever em HTML e CSS o novo design do site

### ISSUE THREAD

**Issue by lfzawacki** [soberanatv/soberanatv.github.io#9]
Figma do novo design: https://www.figma.com/proto/cwgIN9dYHmFMKuyCCVNQFk/Soberana?node-id=213%3A1194&starting-point-node-id=213%3A1194&scaling=contain&show-proto-sidebar=1

**Não se apeguem tanto ao TEXTO dos componentes, tudo está sujeito a mudança**

  * [x] #10
  * [x] #11
  * [x] #12
  * [x] #13
  * [x] #14
  * [x] #15
  * [x] #16
  * [x] #17
  * [x] #18

**Comment by JoaoVictor6** [comment]
Essa issue nao deve ser atualizada?

**Comment by Azhariel** [comment]
@lfzawacki revisar o TODO, pelas minhas contas só falta o formulário de entrar em contato por email; o que falta no restante é só o conteúdo de texto mesmo
